//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrimes.PrimesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrimesService.IPrimesService")]
    public interface IPrimesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimesService/IsPrime", ReplyAction="http://tempuri.org/IPrimesService/IsPrimeResponse")]
        bool IsPrime(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimesService/GetPrimes", ReplyAction="http://tempuri.org/IPrimesService/GetPrimesResponse")]
        int[] GetPrimes(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimesService/GetPrimesBetween", ReplyAction="http://tempuri.org/IPrimesService/GetPrimesBetweenResponse")]
        int[] GetPrimesBetween(int low, int high);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimesServiceChannel : WebPrimes.PrimesService.IPrimesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimesServiceClient : System.ServiceModel.ClientBase<WebPrimes.PrimesService.IPrimesService>, WebPrimes.PrimesService.IPrimesService {
        
        public PrimesServiceClient() {
        }
        
        public PrimesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsPrime(int value) {
            return base.Channel.IsPrime(value);
        }
        
        public int[] GetPrimes(int value) {
            return base.Channel.GetPrimes(value);
        }
        
        public int[] GetPrimesBetween(int low, int high) {
            return base.Channel.GetPrimesBetween(low, high);
        }
    }
}
